### ISSUE TITLE
If shot clock is not displayed, the hooter still goes off. 

### ISSUE THREAD

**Issue by asahani** [wraus/scoreboardWeb#105]
The hooter should be disabled if the shot clock is disabled as they intend to run their own physical shot clocks at international games.

**Comment by hayrich** [comment]
Ok, you mean when shot clock is disabled from Game Settings, as shot clock can also be disabled when quarter time is less than shot clock time.
I'll fix now

**Comment by hayrich** [comment]
Fixed
