### ISSUE TITLE
Game and shot clock tenths buttons flicker

### ISSUE THREAD

**Issue by david2202** [wraus/scoreboardWeb#107]
The game and shot clock tenths of a second adjustment buttons now have a noticeable flicker.  I think this is being caused by the event listeners on the "secondTenthsUpdate" which are always calling the updateGameControlButtons and updateShotControlButtons.  If you remove these calls, the flicker goes away.

**Comment by david2202** [comment]
It's flickering every second, when the tenths of a second field equals zero.  This disables the button for a tenth of a second and then it gets re-enabled again.

**Comment by david2202** [comment]
Perhaps while the clock is running we should disable all of the buttons, and then call updateGameControlButtons and updateShotControlButtons when the clock is stopped for any reason?

**Comment by hayrich** [comment]
The problem with disabling all the time controls while the clock is running gives the impression that the clock must be stopped to edit the times. For speed of time change I wanted the scorer to be able to click to change times at any time which automatically pauses the clocks. I'll look what else we can do to prevent flicker of tenths time controls.

**Comment by hayrich** [comment]
I've got a fix for this and will provide a pull request shortly

@wraus/scoreboard-devs
