### ISSUE TITLE
When shot clock disappears at < 40 secs, quarter box should not resize or relocate

### ISSUE THREAD

**Issue by david2202** [wraus/scoreboardWeb#112]
This might be a personal preference, but I don't like elements moving around on the scoreboard while the game is in progress.  Currently when the shot clock disappears after the game clock goes below 40 seconds, the quarter box enlarges to occupy all of the space.  Looking at the code, this looks like it might have been deliberate by @asahani, so feel free to disagree!

@wraus/scoreboard-devs

**Comment by hayrich** [comment]
closed as no longer relevant, superseded by #161
