### ISSUE TITLE
Time clock and shot clock don't add up

### ISSUE THREAD

**Issue by david2202** [wraus/scoreboardWeb#135]
Steps to reproduce:
1. Reset the quarter (game clock = 8:00, shot clock = 0:40)
2. Start the clock
3. Let the game and shot clock run down until the shot clock reaches zero
4. Game clock is now 7:20.9 and shot clock = 0:40

The shot clock has only run for 39.1 seconds.  Looking at the screen, I think the shot clock is getting reset as soon as it gets to < 1 second so it doesn't run off the last 0.9 of a second.

@wraus/scoreboard-devs

**Comment by david2202** [comment]
I have debugged this, and the targetAchieved event fires when there is still 0.9 seconds left on the clock.  This is true for both the shot clock and the game clock.  This could be a bug in the [easytimer.js](http://albert-gonzalez.github.io/easytimer.js/) library when the precision is tenths of a second.

**Comment by hayrich** [comment]
Fixed in pull request #137

**Comment by hayrich** [comment]
Also created a pull request to merge fix into easytimer.js
https://github.com/albert-gonzalez/easytimer.js/pull/3
