### ISSUE TITLE
Option for a fifth quarter.

### ISSUE THREAD

**Issue by asahani** [wraus/scoreboardWeb#138]
Hi Aman, wow you guys are working hard!

I have just looking through the comments on the edits you are all working on, I saw one mention OT, it triggered a thought, these is overtime on a drawn game. 

Is it too late to add a 5th quarter called OT, I can check the time length for it as it is shorter than the standard 8min or if simpler leave as 8 and we just set the time before starting the clock?

Cheers 

Nick

**Comment by david2202** [comment]
Currently the quarter validation only allows a maximum of four, but when the game clock runs out at the end of quarter 4 it changes to quarter 5.  You can then adjust the time manually.

**Comment by hayrich** [comment]
Nick was satisfied with the approach above as per David's comments "Currently the quarter validation only allows a maximum of four, but when the game clock runs out at the end of quarter 4 it changes to quarter 5. You can then adjust the time manually."
