### ISSUE TITLE
Shot clock number should disappears (but the box is always visible) when the game clock is under 40s AND the shot clock if reset is equal to or higher than the Game clock

### ISSUE THREAD

**Issue by hayrich** [wraus/scoreboardWeb#159]
@nsanders requested:
"Function for when shot clock is under 40s and the shot clock disappears, the coach found an oversight by me, this function needs to be amended to - The shot clock number disappears (but the box is always visible) when the game clock is under 40s AND the shot clock if reset is equal to or higher than the Game clock. As an example currently the game clock is at say 50 seconds, the shot clock reset to 40s, then as they count down and the game clock gets to 40s and the shot clock is at 30s, then in the current build the shot clock disappears but needs to be visible as it is 10s behind the Game clock."

**Comment by hayrich** [comment]
@nsanders88 can you verify the following behaviour is correct:

I have removed the functionality whereby when the game clock is less than the remaining shot clock the shot clock is hidden. 
Instead, now when the shot clock is reset to 40 or 15 then we check if the game clock time remaining is less than the reset shot clock time and if it is then reset the shot clock however hide it from the scoreboard and disable reset shot clock buttons.
If game time is adjusted to being greater than the shot clock time then shot clock is displayed once more and reset buttons are enabled.

**Comment by david2202** [comment]
Closed. Fixed in pull request #166
