### ISSUE TITLE
Shot clock doesn't stop and sound doesn't play when both scorer and scoreboard tabs in same window

### ISSUE THREAD

**Issue by david2202** [wraus/scoreboardWeb#42]
After the latest merge, the shot clock isn't quite right.  Steps to reproduce:
1. Start the clock
2. Click on reset 15
3. Start the clock
4. Switch to the scoreboard

When the shot clock gets to zero, nothing happens.  If you switch back to the scorer application the shot clock is still counting down.

This only happens when both scoreboard and scorer apps are running as tabs is the same window.  If you run them as separate windows then it works OK.

**Comment by david2202** [comment]
This is a limitation of the timer library. In practice, the scoreboard and scorer pages will always run in separate windows so this shouldn't be a problem.

**Comment by hayrich** [comment]
The minimum interval for inactive tabs in modern browers (like Chrome and Firefox) is 1000ms. This limit causes that the timer to stop when the tab is inactive (or the browser is minimized). If you want to use the timer for background tasks, don't use tenth of seconds precision.
