### ISSUE TITLE
Alternate controls for shot clock and timer

### ISSUE THREAD

**Issue by david2202** [wraus/scoreboardWeb#56]
Do you think something like [this](http://www.virtuosoft.eu/code/bootstrap-touchspin/) would look better for adjusting the clocks on the scorer page?

@wraus/scoreboard-devs

**Comment by david2202** [comment]
Or even use the same position of the controls that we have on the score and timeouts?  Those buttons are bigger and as they are at opposite ends of the control it won't be so easy to accidentally click on the wrong one if you have fat fingers.

**Comment by hayrich** [comment]
agreed

**Comment by david2202** [comment]
Fixed by @asahani in the latest UI changes.  Clock controls are now the same as the score controls.
