### ISSUE TITLE
For commands with no action, should action be null?

### ISSUE THREAD

**Issue by david2202** [wraus/scoreboardWeb#59]
In the Scoreboard object, currently when a command has no action we make the action the same as the command.  Now that we are logging these objects as XML, it looks a bit strange that they are duplicated.  Should we change it so that if a command doesn't really need an action, then the action is null?

@wraus/scoreboard-devs

**Comment by hayrich** [comment]
The command is what is used in the scoreboard to trigger events, whereas the action is just the action to record in log. Command can be null in cases where we don't need to trigger events, whereas action is always populated. When duplicated we could either just leave action blank or put a more descriptive message.

**Comment by hayrich** [comment]
fixed in latest pull request #72
