### ISSUE TITLE
mac hotspot

### ISSUE THREAD

**Issue by hayrich** [wraus/scoreboardWeb#62]
With a mac "the one big limitation is that you can’t both be connected to a Wi-Fi network and host a Wi-Fi network at the same time". 
However if the mac is connected over the ethernet you can then "hotspot" share the mac over wifi.

http://www.howtogeek.com/214053/how-to-turn-your-mac-into-a-wi-fi-hotspot/ 

@wraus/scoreboard-devs

**Comment by david2202** [comment]
[Bluetooth uses short-range radio waves over distances up to approximately 10 metres](https://en.wikipedia.org/wiki/Personal_area_network)

I think wi-fi is the way to go.
