### ISSUE TITLE
When quarter ends, scoreboard clock shows 1:00

### ISSUE THREAD

**Issue by david2202** [wraus/scoreboardWeb#95]
When the quarter ends, the scoreboard clock resets itself to 1:00 while the scorer clock shows 08:00.

When you start the clock, the scoreboard clock starts counting down from 01:00 while the scorer clock doesn't count down at all.  The scorer and scoreboard shot clocks count down correctly.

@wraus/scoreboard-devs

**Comment by david2202** [comment]
Still not fixed by latest pull request.  The scoreboard clock shows 1:00 after the quarter has ended.  Starting the clock again does fix it, and the clocks then countdown properly.

@hayrich

**Comment by hayrich** [comment]
I can't reproduce can others please try?

**David's steps to reproduce:**
- Refresh both screens  
- Now start clock
- Then stop clock
- Then use minus buttons to adjust game clock to 1:01
- Then start clock again
- Clock should now be counting down
- Shot clock disappeared at 40 seconds
- 20 seconds
- 10 seconds
- Clock now reads 01:00 on scoreboard
- Quarter has changed to 2
- Shot clock has reappeared and is 00

I don't get this, for me scoreboard game clock read 00:00 after quarter end

**Comment by hayrich** [comment]
David, please retest
