### ISSUE TITLE
If clock is stopped and the seconds and tenths of a second are zero, reducing the minutes to zero wraps back to 8 minutes

### ISSUE THREAD

**Issue by david2202** [wraus/scoreboardWeb#97]
This is inconsistent with the other controls, where the minus button gets disabled when you reach the lower limit.

I suspect this is being caused by an event somewhere to reset the clock when it reaches zero.

This is not a huge issue, as it mainly affects when you are trying to reduce the clock to under a minute to test the end of quarter functionality.  You need to remember to reduce the seconds first and then the minutes.

@wraus/scoreboard-devs

**Comment by hayrich** [comment]
0 is being treated as undefined, will fix now
